### ISSUE TITLE
I found that the web version of the light can't adjust the color and can adjust the lighting effect. Is it my own problem?

### ISSUE THREAD

**Issue by EasonQian1** [vial-kb/vial-web#1]
I found that the web version of the light can't adjust the color and can adjust the lighting effect. Is it my own problem?

**Comment by EasonQian1** [comment]
![9P0RQI4L8{5{DA3NM(C$6BT](https://user-images.githubusercontent.com/98533237/174347893-c460b405-e859-4ae6-a113-6d093e2a48fe.png)
![5A`V)WU9U25%~S6UPJN AMH](https://user-images.githubusercontent.com/98533237/174347899-2355b812-9c3c-4d62-9085-0fe955d7cb45.png)

**Comment by alexkang** [comment]
+1. Also running into this issue whenever I try to open the color picker for lighting on web. Doesn't happen on the Python QT version.

Got the message that EasonQian1 ran into and in addition, these console logs. 
![image](https://github.com/vial-kb/vial-web/assets/5171499/a7e88c91-6f62-47f3-bf87-2aaec5401484)

I'm using Google Chrome on Mac OS.

**Comment by xyzz** [comment]
fixed in 48d9de3d30d38248dd9fa46cb080a45640979f11 & b51164b8a945a95a8a296fb411ae74d571706c5c
