### ISSUE TITLE
Would like to help create a dockerfile

### ISSUE THREAD

**Issue by whitehatmiddleman** [vial-kb/vial-web#3]
Hello, I would like to help create a dockerfile for this, but I was curious which type of distro were you able to build this from? I'm currently using an ubuntu:22.04 image and it seems that when I compile cpython it doesn't include the ssl modules needed to install some of the other dependencies during the build.

Basically if I were to run the build-deps.sh from vanilla, I get the following error logs, which tells me the pip is not able to make https call to pull the rest of the sip dependencies:
```
Installed /root/vial-web/deps/venv/lib/python3.11/site-packages/sip-5.5.0-py3.11-linux-x86_64.egg
Processing dependencies for sip==5.5.0
Searching for toml
Reading https://pypi.org/simple/toml/
Download error on https://pypi.org/simple/toml/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'toml' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for toml
error: Could not find suitable distribution for Requirement.parse('toml')
```

**Comment by xyzz** [comment]
Try installing libssl-dev

**Comment by whitehatmiddleman** [comment]
Thanks for the update, I've created a pull request to include the dockerfile.
